export const industries = [
  { value: "agriculture", label: "Agriculture, Forestry & Fishing" },
  { value: "mining", label: "Mining & Quarrying" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "utilities", label: "Electricity, Gas & Water Supply" },
  { value: "construction", label: "Construction" },
  { value: "retail", label: "Wholesale & Retail Trade" },
  { value: "transport", label: "Transport, Storage & Communication" },
  { value: "accommodation", label: "Accommodation & Food Service Activities" },
  { value: "financial", label: "Financial & Insurance Activities" },
  { value: "realestate", label: "Real Estate Activities" },
  { value: "professional", label: "Professional, Scientific & Technical Activities" },
  { value: "administrative", label: "Administrative & Support Service Activities" },
  { value: "public", label: "Public Administration & Defence" },
  { value: "education", label: "Education" },
  { value: "healthcare", label: "Human Health & Social Work Activities" },
  { value: "arts", label: "Arts, Entertainment & Recreation" },
  { value: "ict", label: "Information & Communication Technology" },
  { value: "other", label: "Other Service Activities" },
]
